In [1]:
import numpy as np

In [2]:
# sigmoid function  
def nonlin(x,deriv=False):  
    if(deriv==True):  
        return x*(1-x)  
    return 1/(1+np.exp(-x))  

In [3]:
# input dataset  
X = np.array([  [0,0,1],  
                [0,1,1],  
                [1,0,1],  
                [1,1,1] ])  

In [4]:
# output dataset              
y = np.array([[0,0,1,1]]).T  

In [31]:
# seed random numbers to make calculation  
# deterministic (just a good practice)  
np.random.seed(1)  

In [32]:
# initialize weights randomly with mean 0  
syn0 = 2*np.random.random((3,1)) - 1  

In [33]:
syn0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [36]:
for iter in xrange(10000):  
  
    # forward propagation  
    l0 = X  
    l1 = nonlin(np.dot(l0,syn0))  

    # how much did we miss?  
    l1_error = y - l1  
    
    # multiply how much we missed by the   
    # slope of the sigmoid at the values in l1 
    #很多奥秘隐藏于此
    l1_delta = l1_error * nonlin(l1,True)  

    # update weights  
    #神经网络中的一切都为这行操作服务
    syn0 += np.dot(l0.T,l1_delta)  
    

In [37]:
for line in X:
    print line,syn0.T[0], np.dot( line, syn0 ) , nonlin(np.dot( line, syn0 )) 

[0 0 1] [ 10.38040701  -0.20641179  -4.98452047] [-4.98452047] [ 0.00679655]
[0 1 1] [ 10.38040701  -0.20641179  -4.98452047] [-5.19093226] [ 0.005536]
[1 0 1] [ 10.38040701  -0.20641179  -4.98452047] [ 5.39588654] [ 0.99548528]
[1 1 1] [ 10.38040701  -0.20641179  -4.98452047] [ 5.18947475] [ 0.99445597]


In [40]:
# randomly initialize our weights with mean 0  
syn0 = 2*np.random.random((3,4)) - 1  
syn1 = 2*np.random.random((4,1)) - 1  
  
for j in xrange(100000):  

    # Feed forward through layers 0, 1, and 2  
    l0 = X  
    l1 = nonlin(np.dot(l0,syn0))  
    l2 = nonlin(np.dot(l1,syn1))  
  
    # how much did we miss the target value?  
    #计算输出与我们预定的结果的差距,如果l2_error很大，说明误差很大，
    #需要对W进行较大的调整
    l2_error = y - l2  
      
    if (j% 10000) == 0:  
        print "Error:" + str(np.mean(np.abs(l2_error)))  
          
    # in what direction is the target value?  
    # were we really sure? if so, don't change too much.
    #求l2的梯度
    l2_delta = l2_error*nonlin(l2,deriv=True)  
  
    # how much did each l1 value contribute to the l2 error (according to the weights)? 
    #算出l1对追踪结果误差的影响,w1.T是w1的梯度
    l1_error = l2_delta.dot(syn1.T)  
      
    # in what direction is the target l1?  
    # were we really sure? if so, don't change too much.  
    #求l1的梯度
    l1_delta = l1_error * nonlin(l1,deriv=True)  

    #对W0，W1进行修正
    syn1 += l1.T.dot(l2_delta)  
    syn0 += l0.T.dot(l1_delta)  

Error:0.491749353585
Error:0.00496935711177
Error:0.00342223413157
Error:0.00275673103196
Error:0.00236629812271
Error:0.00210271350559
Error:0.0019097054546
Error:0.00176065436734
Error:0.00164113774169
Error:0.00154257998295
